# Simple Docker Compose that pulls Nginx and PHP 8.3
services:
  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html
    networks:
      - crackme-webserver
  php:
    image: php:8.3-fpm
    volumes:
      - ./html/:/var/www/html
    networks:
      - crackme-webserver
networks:
  crackme-webserver: